### ISSUE TITLE
from multiprocessing import Pipe, Process, Array, Lock  不能引用 Cannot reference Pipe

### ISSUE THREAD

**Issue by Dailywuxi** [ItGarbager/aimcf_yolov5#12]
from multiprocessing import Pipe, Process, Array, Lock  不能引用 Cannot reference 
Pipe, Process, Array, Lock 都是红色的不能引用，什么原因啊 小白不懂。

‘Pipe, Process, Array, Lock’ All are red and cannot be quoted ？I'm a novice.

**Comment by ItGarbager** [comment]
这是python自带的标准库，如果引入异常，请检查你的python版本
