### ISSUE TITLE
大佬,cf.pt可以给个链接下载吗?

### ISSUE THREAD

**Issue by tom-field** [ItGarbager/aimcf_yolov5#5]

**Comment by ItGarbager** [comment]
下班回去我上传发你



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月14日 12:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [ItGarbager/aimcf_yolov5] 大佬,cf.pt可以给个链接下载吗? (Issue #5) |

**Comment by ItGarbager** [comment]
v2分支里我刚刚看了是有的啊
