### ISSUE TITLE
自瞄不生效

### ISSUE THREAD

**Issue by T0oby** [ItGarbager/aimcf_yolov5#6]
使用main.py 运行后 有悬浮窗以及方框显示 ，但是开启自瞄鼠标没有响应 按下侧键重新开关也无反应。使用的是罗技鼠标 电脑带有最新的ghub

**Comment by ItGarbager** [comment]
当前驱动兼容性可能有问题，尝试使用 win32api 实现鼠标移动

**Comment by T0oby** [comment]
使用 test_move.py 时鼠标移动是生效的 。

**Comment by ItGarbager** [comment]
尝试使用管理员启动，如果还不生效，说明现在cf屏蔽了驱动
