### ISSUE TITLE
瞄不准

### ISSUE THREAD

**Issue by hurangit** [ItGarbager/aimcf_yolov5#8]
在游戏外面用图片测试的话 是瞄的很准，但是在游戏里面就瞄不准了 这是怎么回事

**Comment by ItGarbager** [comment]
游戏内鼠标速度调高，自己测试，调到一个准确的速度



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月27日 02:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [ItGarbager/aimcf_yolov5] 瞄不准 (Issue #8) |

在游戏外面用图片测试的话 是瞄的很准，但是在游戏里面就瞄不准了 这是怎么回事
