### ISSUE TITLE
罗技鼠标 无法控制其移动光标

### ISSUE THREAD

**Issue by PlutoNameless** [ItGarbager/aimcf_yolov5#9]
手动移动可以在人物上自动开火，但是光标无法自动移动。
已经安装Ghub，使用的是罗技G502 Hero

**Comment by ItGarbager** [comment]
尝试安装旧版本ghub



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月12日 06:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [ItGarbager/aimcf_yolov5] 罗技鼠标 无法控制其移动光标 (Issue #9) |

手动移动可以在人物上自动开火，但是光标无法自动移动。
已经安装Ghub，使用的是罗技G502 Hero
